##### Hinweis: In den Aufgaben kann es sinnvoll sein sich über die Datenstrukturen Gedanken zu machen.
# Aufgabe 1.1
### Sie finden beigefügt eine Datei mit dem Namen Uni_Marburg_Wikipedia.txt. In dieser Datei ist der Wikipediaartikel (Stand 18.10.2017) unserer Universität gespeichert.
## a) Öffen Sie die Datei, geben Sie den kompletten Text aus und schließen Sie dann den Datenstrom. (2,5 P.)

In [73]:
Datei = open("./Uni_Marburg_Wikipedia.txt")
Dateitext = Datei.read()
print(Dateitext)
Datei.close()

Philipps-Universitaet Marburg 
Die Philipps-Universitaet Marburg ( historisch Alma Mater Philippina ) wurde 1527 gegruendet und umfasst heute 16 Fachbereiche deren Einrichtungen ueber das Marburger Stadtgebiet verteilt sind sowie eine Verwaltung . Mit ueber 26.497 Studierenden ( 2016 ) zaehlt sie zu den mittelgrossen deutschen Volluniversitaeten . Sie besitzt in mehreren Fachbereichen ( Medizin Chemie Psychologie etc. ) ein Renommee und gilt hier als besonders drittmittel- und forschungsstark . 
Die Universitaet wurde im Jahr 1527 von Landgraf Philipp dem Grossmuetigen als protestantische Hochschule gegruendet und ist damit die aelteste noch bestehende Universitaet der Welt die auf eine protestantische Gruendung zurueckgeht . 
Geschichte 
Gruendungsjahre 
Landgraf Philipp der Grossmuetige Steinrelief Philippstein von 1542 
Am 1. Juli 1527 weihte der landgraefliche Kanzler Johann Feige die von Landgraf Philipp gegruendete Universitaet feierlich ein . Ihr gehoerten damals elf Professoren

## b) Lassen Sie berechnen, wie oft das Wort Informatik vorkommt. (2 P.)

In [74]:
Anzahl = 0
Dateitext_aufgeteilt = Dateitext.split()
for Wort in Dateitext_aufgeteilt:
    if Wort == 'Informatik':
        Anzahl += 1
print(Anzahl)

1


## c) Welches sind die 10 Worte, die im Text am öftesten vorkommen? Geben Sie diese als Liste, oder in einer Menge aus. (3,5 P.)

In [82]:
Einzelwortliste = []
Einzelwortanzahl = []
for Wort in Dateitext_aufgeteilt:
    if not Wort in Einzelwortliste:
        Einzelwortliste.append(Wort)
        Einzelwortanzahl.append(1)
    else:
        Einzelwortanzahl[Einzelwortliste.index(Wort)] += 1

In [84]:
#Dateitext_aufgeteilt.index('und')


for Wort in Einzelwortanzahl

14

In [68]:
print(len(Einzelwortliste), len(Einzelwortliste2))

3676 1604


In [83]:
for n, Position in enumerate(Einzelwortanzahl):
    if n >=5:
        print(n, Einzelwortliste[n])

5 Alma
6 Mater
7 Philippina
8 )
9 wurde
10 1527
11 gegruendet
12 und
13 umfasst
14 heute
15 16
16 Fachbereiche
17 deren
18 Einrichtungen
19 ueber
20 das
21 Marburger
22 Stadtgebiet
23 verteilt
24 sind
25 sowie
26 eine
27 Verwaltung
28 .
29 Mit
30 26.497
31 Studierenden
32 2016
33 zaehlt
34 sie
35 zu
36 den
37 mittelgrossen
38 deutschen
39 Volluniversitaeten
40 Sie
41 besitzt
42 in
43 mehreren
44 Fachbereichen
45 Medizin
46 Chemie
47 Psychologie
48 etc.
49 ein
50 Renommee
51 gilt
52 hier
53 als
54 besonders
55 drittmittel-
56 forschungsstark
57 Universitaet
58 im
59 Jahr
60 von
61 Landgraf
62 Philipp
63 dem
64 Grossmuetigen
65 protestantische
66 Hochschule
67 ist
68 damit
69 die
70 aelteste
71 noch
72 bestehende
73 der
74 Welt
75 auf
76 Gruendung
77 zurueckgeht
78 Geschichte
79 Gruendungsjahre
80 Grossmuetige
81 Steinrelief
82 Philippstein
83 1542
84 Am
85 1.
86 Juli
87 weihte
88 landgraefliche
89 Kanzler
90 Johann
91 Feige
92 gegruendete
93 feierlich
94 Ihr
95 gehoerten
96 damals
97 el

1517 deutschlandweite
1518 Besonderheit
1519 stellte
1520 Konrad-Biesalski-Haus
1521 Hier
1522 Menschen
1523 koerperlicher
1524 Behinderung
1525 hohem
1526 Assistenzbedarf
1527 Wohnmoeglichkeit
1528 geschaffen
1529 Modell
1530 dieses
1531 immer
1532 Alleinstellungsmerkmal
1533 Ein
1534 architektonisches
1535 vorbeugenden
1536 Brandschutzes
1537 Landschaft
1538 Rettungsrutschen
1539 Campusleben
1540 Neben
1541 Kultur-
1542 Sport-
1543 Freizeitangeboten
1544 So
1545 stehen
1546 ihnen
1547 Hochschulsport
1548 fast
1549 verschiedene
1550 Sportarten
1551 Angeboten
1552 diverse
1553 Ball-
1554 Teamsportarten
1555 Rugby
1556 Lacrosse
1557 American
1558 Football
1559 Wasser-
1560 Reit-
1561 Kampfsport
1562 Yoga
1563 Shiatsu
1564 Darueber
1565 findet
1566 jedes
1567 Tag
1568 SportDies
1569 wo
1570 ueberall
1571 Sportveranstaltungen
1572 abgedeckt
1573 Sprachenzentrum
1574 ermoeglicht
1575 aller
1576 erlernen
1577 Dabei
1578 fachspezifische
1579 Sprachenkurse
1580 kostenlose
1581 Dienste
1582 un

# Aufgabe 1.2
## Es ist folgender Text gegeben:
Dr. Thomas Fober ist Dozent am Fachbereich 12 der Philipps-Universitaet Marburg. Im Wintersemster 2017/18 liesst er unter anderem die Vorlesung Maschinelles Lernen. Sein Buero befindet sich in 04C20a.
## a) Geben Sie an, welche Wörter sowohl in diesem Text, als auch in dem Wikipediaartikel vorkommen. (2 P.)

In [93]:
myStr = "Dr. Thomas Fober ist Dozent am Fachbereich 12 der Philipps-Universitaet Marburg. Im Wintersemster 2017/18 liesst er unter anderem die Vorlesung Maschinelles Lernen. Sein Buero befindet sich in 04C20a."
for Wort in set(myStr.split()):
    if Wort in set(Dateitext_aufgeteilt):
        print(Wort)

in
12
Im
am
unter
sich
Fachbereich
Philipps-Universitaet
er
anderem
die
der
ist


## b) Berechnen Sie mit Python die Menge, die alle Charakter speichert, die im ASCII-Alphabet nach dem "p" kommen. Verwenden Sie keine Schleife. (4 P.)
### Für eine Lösung mit Schleife (1,5 P.)
##### Hinweis: Sei a eine Variable, die ein Charakter enthält. Ein Vergleich "p"< a gibt genau dann true zurück, wenn a im ASCII-Alphabet nach p kommt, z.B. ist "p"<"t" true.

In [134]:
myStr = "Dr. Thomas Fober ist Dozent am Fachbereich 12 der Philipps-Universitaet Marburg. Im Wintersemster 2017/18 liesst er unter anderem die Vorlesung Maschinelles Lernen. Sein Buero befindet sich in 04C20a."

Buchstabenliste = sorted(list(set(myStr)))                 # Aufgabe komische gesteltt!
print(Buchstabenliste[Buchstabenliste.index('p') + 1::])
print(len(Buchstabenliste[Buchstabenliste.index('p') + 1::]))

['r', 's', 't', 'u', 'v', 'z']
6


# Aufgabe 1.3
### Eine Matrix kann in Python durch zwei verschachtelte Listen dargestellt werden. z.B.:
$$
\left(
\begin{array}{ll}
4 & 5\\
3 & 2
\end{array}
\right) =
\left[[4,5],[3,2]\right]
$$
### Benutzen Sie in allen Aufgabenteilen keine konkreten Werte, sondern arbeiten Sie mit den Positionsangaben in der Matrix, so dass ihre Implementierung bei jeder möglichen Eingabe funktioniert.
## a) Geben Sie den Python-Code an, der eine 3x3-Matrix transponieren lässt. (1,5 P.)
##### Informationen zum Transponieren: https://www.mathebibel.de/transponierte-matrix

In [172]:
# Ein Beispiel für eine 3x3-Matrix an der Sie Ihre Implementierung testen können.
matrix = [[1,2,3],[4,5,6],[7,8,9],[10,11,12]]
matrix_transponiert = [[0 for x in range(len(matrix))] for y in range(len(matrix[1]))]

for i in range(len(matrix[1])):
    for j in range(len(matrix)):
        matrix_transponiert[i][j] = matrix[j][i]

print(matrix)
matrix_transponiert

[[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]]


[[1, 4, 7, 10], [2, 5, 8, 11], [3, 6, 9, 12]]

In [164]:
#               a11 a12 a13     a11 a21 a31  
#               a21 a22 a23     a12 a22 a32
#               a31 a32 a33     a13 a23 a33

matrix = [[1,2,3],[0,1,0],[-1,0,3],[-1,0,3]]
matrix[1][1] = 6
len(matrix[1])

3

## b) Geben Sie den Python-Code an, der die Determinante einer 3x3-Matrix berechnet. (2,5 P.)
##### Informationen zum Berechnen einer 3x3-Determinante: https://www.mathebibel.de/3x3-determinanten-berechnen

In [188]:
# Ein Beispiel für eine 3x3-Matrix an der Sie Ihre Implementierung testen können.
matrix = [[1,2,3],[0,1,0],[-1,0,3]]
matrix_dete = 0

for i in range(3):
    matrix_dete += matrix[0][i]*matrix[1][(i + 1)%3]*matrix[2][(i + 2)%3]
for i in range(3):
    matrix_dete -= matrix[0][i]*matrix[1][(i - 1)%3]*matrix[2][(i - 2)%3]

    
for i in range(3):
    Hauptdiagonale = 1
    for j in range(3):
            Hauptdiagonale = Hauptdiagonale *matrix[j][(i + j)%3]
    matrix_dete += Hauptdiagonale
for i in range(3):
    Nebendiagonale = 1
    for j in range(3):
        Nebendiagonale = Nebendiagonale *matrix[j][(i - j)%3]
    matrix_dete -= Nebendiagonale

matrix_dete

12

In [182]:
import numpy as np

In [179]:
npmatrix = np.matrix(matrix)
npmatrix
np.linalg.det(npmatrix)

6.0

In [185]:
for i in range(10):
    print(i-3, (i-3)%3)

-3 0
-2 1
-1 2
0 0
1 1
2 2
3 0
4 1
5 2
6 0


## c) Geben Sie den Python-Code an, der zwei 3x3 Matritzen multiplizieren lässt. (3 P.)
##### Informationen zur Matrixmultiplikation: http://www.mathematrix.de/matrixmultiplikation/

In [189]:
# Ein weiteres Beispiel für eine 3x3-Matrix an der Sie Ihre Implementierung testen können.
matrix = [[1,2,3],[0,1,0],[-1,0,3]]
matrix2 = [[4,1,0],[2,-1,-2],[-2,0,1]]

L_matrix = [[0,0,0],[0,0,0],[0,0,0]]

for i in range(3):
    for j in range(3):
        L_matrix[i][j] =(
 matrix[i][0]*matrix2[0][j] + matrix[i][1]*matrix2[1][j] + matrix[i][2] * matrix2[2][j]
        )
L_matrix

[[2, -1, -1], [2, -1, -2], [-10, -1, 3]]

In [195]:
npmatrix1 = np.array(matrix)
npmatrix2 = np.array(matrix2)
print(np.dot(npmatrix1, npmatrix2))

[[  2  -1  -1]
 [  2  -1  -2]
 [-10  -1   3]]
